Product:
  type: entity
  table: product
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      generator:
        strategy: SEQUENCE
  fields:
    libelle:
      type: string
      nullable: true
      length: 32
      options:
        fixed: false
    prix:
      type: string
      nullable: true
      length: 32
      options:
        fixed: false

  lifecycleCallbacks: {}
